# Generated by Django 5.0.2 on 2024-05-03 08:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('반포고', '반포고'), ('상문고', '상문고'), ('서울고', '서울고'), ('서문여고', '서문여고')], default='세화고', max_length=10, verbose_name='고등학교')),
                ('name', models.CharField(max_length=10, verbose_name='학생 이름')),
                ('university', models.CharField(default='Unknown', max_length=20, verbose_name='대학교')),
                ('major', models.CharField(default='Unknown', max_length=20, verbose_name='학과')),
                ('title', models.CharField(default='애플과학 수강후기', max_length=100, verbose_name='제목')),
                ('content', models.TextField(max_length=1500, verbose_name='수강 후기')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 시간')),
            ],
            options={
                'verbose_name': '수강후기',
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, verbose_name='학교')),
                ('grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년')),
                ('student_name', models.CharField(max_length=100, verbose_name='학생 이름')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='부모님 핸드폰 번호')),
                ('note', models.CharField(max_length=200, verbose_name='비고')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('school', models.CharField(blank=True, choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, null=True)),
                ('grade', models.CharField(blank=True, choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, null=True)),
                ('subjects', models.CharField(choices=[('물리', '물리'), ('화학', '화학'), ('지구과학', '지구과학'), ('생명과학', '생명과학'), ('통합과학', '통합과학')], max_length=10, null=True)),
                ('payment_count', models.IntegerField(default=12)),
                ('payment_request', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('posted_in', models.CharField(choices=[('community', '커뮤니티'), ('main', '메인'), ('management', '행정')], default='main', max_length=10, verbose_name='종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_school', models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, verbose_name='학교')),
                ('course_grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년')),
                ('course_subjects', models.CharField(choices=[('물리', '물리'), ('화학', '화학'), ('지구과학', '지구과학'), ('생명과학', '생명과학'), ('통합과학', '통합과학')], max_length=20, verbose_name='과목')),
                ('course_day', models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일')], max_length=10, verbose_name='수업 요일')),
                ('course_time', models.TimeField(verbose_name='수업 시작 시간')),
                ('course_room', models.CharField(choices=[('402', '402'), ('403', '403'), ('404', '404'), ('408', '408'), ('409', '409'), ('415', '415')], max_length=10, null=True, verbose_name='강의실')),
                ('course_students', models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='선생')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='common.course'),
        ),
    ]
