# Generated by Django 5.0.2 on 2024-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '출석', 'verbose_name_plural': '출석'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '수강후기', 'verbose_name_plural': '수강후기'},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name': '대기목록', 'verbose_name_plural': '대기목록'},
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
