# Generated by Django 5.0.2 on 2024-03-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(
                choices=[("student", "학생"), ("teacher", "선생님"), ("staff", "직원")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True,
                choices=[
                    ("세화고", "세화고"),
                    ("세화여고", "세화여고"),
                    ("반포고", "반포고"),
                    ("상문고", "상문고"),
                    ("직접입력", "직접입력"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
