# Generated by Django 5.0.2 on 2024-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_attendance_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, verbose_name='학교')),
                ('grade', models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년')),
                ('student_name', models.CharField(max_length=100, verbose_name='학생 이름')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='부모님 핸드폰 번호')),
                ('note', models.CharField(max_length=200, verbose_name='비고')),
            ],
            options={
                'verbose_name': '블랙리스트',
                'verbose_name_plural': '블랙리스트',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.CharField(blank=True, choices=[('물리', '물리'), ('화학', '화학'), ('지구과학', '지구과학'), ('생명과학', '생명과학'), ('통합과학', '통합과학')], max_length=10, null=True),
        ),
    ]
