# Generated by Django 5.0.2 on 2024-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subject_remove_user_subjects_user_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_subjects',
        ),
        migrations.AddField(
            model_name='course',
            name='course_biology',
            field=models.BooleanField(default=False, verbose_name='생명과학'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_chemistry',
            field=models.BooleanField(default=False, verbose_name='화학'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_earth_science',
            field=models.BooleanField(default=False, verbose_name='지구과학'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_integrated_science',
            field=models.BooleanField(default=False, verbose_name='통합과학'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_physics',
            field=models.BooleanField(default=False, verbose_name='물리'),
        ),
        migrations.AddField(
            model_name='user',
            name='biology',
            field=models.BooleanField(default=False, verbose_name='생명과학'),
        ),
        migrations.AddField(
            model_name='user',
            name='chemistry',
            field=models.BooleanField(default=False, verbose_name='화학'),
        ),
        migrations.AddField(
            model_name='user',
            name='earth_science',
            field=models.BooleanField(default=False, verbose_name='지구과학'),
        ),
        migrations.AddField(
            model_name='user',
            name='integrated_science',
            field=models.BooleanField(default=False, verbose_name='통합과학'),
        ),
        migrations.AddField(
            model_name='user',
            name='physics',
            field=models.BooleanField(default=False, verbose_name='물리'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
