# Generated by Django 5.0.2 on 2024-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, null=True, verbose_name='학교'),
        ),
    ]
