# Generated by Django 5.0.2 on 2024-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_user_biology_alter_user_chemistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biology',
            field=models.BooleanField(default=False, verbose_name='생명과학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chemistry',
            field=models.BooleanField(default=False, verbose_name='화학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='earth_science',
            field=models.BooleanField(default=False, verbose_name='지구과학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='user',
            name='integrated_science',
            field=models.BooleanField(default=False, verbose_name='통합과학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='physics',
            field=models.BooleanField(default=False, verbose_name='물리'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=50, null=True, verbose_name='학교'),
        ),
    ]
