# Generated by Django 5.0.2 on 2024-05-10 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_user_biology_alter_user_chemistry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date'], 'verbose_name': '출석', 'verbose_name_plural': '출석'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended_at',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='student_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='출석 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='applying_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='대기등록 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='name',
            field=models.CharField(default='test', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='attended_dates',
            field=models.ManyToManyField(blank=True, related_name='attending_students', to='common.attendance', verbose_name='출석 날짜'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='applying_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='대기등록 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='name',
            field=models.CharField(default='test', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='common.course', verbose_name='수업'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsfasdf', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='note',
            field=models.TextField(max_length=500, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='parent_phone',
            field=models.CharField(max_length=20, verbose_name='부모님 전화번호'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='school',
            field=models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=10, verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='부모님 전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='note',
            field=models.TextField(max_length=500, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='parent_phone',
            field=models.CharField(max_length=20, verbose_name='부모님 전화번호'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='school',
            field=models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('연합반', '연합반')], max_length=10, verbose_name='학교'),
        ),
    ]
