# Generated by Django 5.0.2 on 2024-05-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_attendance_student_alter_user_attended_dates_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absent',
            new_name='Absence',
        ),
    ]
