# Generated by Django 5.0.2 on 2024-05-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_rename_absent_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_biology',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_chemistry',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_earth_science',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_physics',
        ),
    ]
