# Generated by Django 5.0.2 on 2024-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_remove_course_course_biology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_integrated_science',
        ),
        migrations.AddField(
            model_name='user',
            name='latest_payment',
            field=models.DateField(blank=True, null=True, verbose_name='최근 결제 날짜'),
        ),
    ]
