# Generated by Django 5.0.2 on 2024-07-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_course_course_integrated_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.CharField(choices=[('physics', '물리'), ('chemistry', '화학'), ('biology', '생명과학'), ('earth_science', '지구과학'), ('integrated_science', '통합과학'), ('special_physics', '특강-물리'), ('special_chemistry', '특강-화학'), ('special_biology', '특강-생명과학'), ('special_earth_science', '특강-지구과학'), ('special_integrated_science', '특강-통합과학')], default='선택과목', max_length=30, verbose_name='선택과목'),
        ),
    ]
