# Generated by Django 5.0.2 on 2024-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_course_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_room',
            field=models.CharField(blank=True, choices=[('402', '402'), ('403', '403'), ('404', '404'), ('408', '408'), ('409', '409'), ('415', '415')], max_length=10, null=True, verbose_name='강의실'),
        ),
    ]
