# Generated by Django 5.0.2 on 2024-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_review_image_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_day',
            field=models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일')], default='일요일', max_length=10, verbose_name='수업 요일'),
        ),
    ]
