# Generated by Django 5.0.2 on 2024-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_course_course_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_time',
            field=models.TimeField(default='10:00', verbose_name='수업 시작 시간'),
        ),
    ]
