# Generated by Django 5.0.2 on 2024-09-10 11:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_course_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='내용'),
        ),
    ]
