# Generated by Django 5.0.2 on 2024-09-14 06:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_board_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='내용'),
        ),
    ]
