# Generated by Django 5.0.2 on 2024-09-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_count',
            field=models.IntegerField(default=0, verbose_name='선택과목수'),
        ),
    ]
