# Generated by Django 5.0.2 on 2024-10-08 08:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_user_courses_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': '블랙리스트', 'verbose_name_plural': '블랙리스트'},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name': '대기리스트', 'verbose_name_plural': '대기리스트'},
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='applying_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='waitlist',
            old_name='applying_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to=settings.AUTH_USER_MODEL, verbose_name='등록한 관리자'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='연락처'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to=settings.AUTH_USER_MODEL, verbose_name='등록한 관리자'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='grade',
            field=models.CharField(choices=[('에비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.CharField(choices=[('에비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('에비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='grade',
            field=models.CharField(choices=[('에비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='비고'),
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('오전', '오전'), ('오후', '오후')], default='오전', max_length=5, verbose_name='제목-시간')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '인수인계',
                'verbose_name_plural': '인수인계',
            },
        ),
    ]
