# Generated by Django 5.0.2 on 2024-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_blacklist_options_alter_waitlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='importance',
            field=models.IntegerField(default=10),
        ),
    ]
