# Generated by Django 5.0.2 on 2024-12-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_review_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['-date'], 'verbose_name': '블랙리스트', 'verbose_name_plural': '블랙리스트'},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'ordering': ['-date'], 'verbose_name': '대기리스트', 'verbose_name_plural': '대기리스트'},
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='grade',
            field=models.CharField(choices=[('예비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.CharField(choices=[('예비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='review',
            name='school',
            field=models.CharField(choices=[('세화고', '세화고'), ('세화여고', '세화여고'), ('반포고', '반포고'), ('상문고', '상문고'), ('서울고', '서울고'), ('서문여고', '서문여고'), ('영동고', '영동고')], default='세화고', max_length=10, verbose_name='고등학교'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('예비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='grade',
            field=models.CharField(choices=[('예비고1', '예비고1'), ('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년')], max_length=10, verbose_name='학년'),
        ),
    ]
